<a href="https://colab.research.google.com/github/Tejas132005/Numpy/blob/main/theoretical_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
# Ans:
# Efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries solidifies its position as the
#   cornerstone of numerical computing in Python.
# NumPy handles advanced mathematical operations such as matrix multiplication, eigenvalue calculation and differential equations. This makes NumPy
#  particularly valuable across a vast range of simulation, modeling, visualization, computational processing and other scientific computing tasks.

In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# Ans:
# np.mean() method returns arithmetic mean
# np. average() function returns the algebraic mean if no additional parameters are specified, but it may also be used to compute a weighted average.

In [ ]:
# Example for mean///
import numpy as np
l = [1,2,3,4,5,6,7,8,9,10]
a = np.array(l)
np.mean(a)

5.5

In [ ]:
# Example for average///
import numpy as np
ll = [1,2,3,4,5,6,7,8,9,10]
a1 = np.array(ll)
weight = np.array([4,5,6,12,15,10,2,8,19,20])
np.average(a1)

5.5

In [ ]:
np.average(a1, weights=weight)

6.574257425742574

In [ ]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# Ans:
# using reverse() function
# using flip() function
# using flipir() function
# using flipud() functio

# Examples:
import numpy as np
l = [1,2,3,4,5,6,7]
a = np.array(l)
np.flip(a)

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
a1 = np.array([[1,2,3,4,5,6,7]])
np.flip(a1)

array([[7, 6, 5, 4, 3, 2, 1]])

In [ ]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
# Ans:
a = np.array([1,2,3,4,5,6])
a.dtype
# Importance
# data types are used to classify one particular type of data. This is important because the specific data type you use will determine what values you
#  can assign to it and what you can do to it (including what operations you can perform on it).

dtype('int64')

In [ ]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
# Ans:
#  ndarray is n dimensional array of same size and type
# Key features of ndarry are:
# structure , creation ,sharing, indexing and slicing, vectoirisation, etc,,,.
# ndarrys in numpy are faster in execution then standard python lists and helps to solve complex mathematical calculations very easily.

In [ ]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
# Ans:
# Performance benifits:
# 1. More memory efficient
# 2. Holds homogeneous data in continues memory location
# 3. Exerute at compiled c speed(faster execution)
# 4. Can handle large data set
# 5. Solves complex calculations very easily

In [ ]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
# Ans:

# numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array where as
#  numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.
# Syntax  :  numpy.vstack(tup) { vstack }, numpy.hstack(tup) { hstack }

In [ ]:
# Example for vstack():
import numpy as np
arr1 = ([[1,2,3,], [4,5,6]])
arr2 = ([[11,12,13],[14,15,16]])
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [ ]:
# Examples for hstack():
import numpy as np
a1 = ([[1,2,3,], [4,5,6]])
a2 = ([[11,12,13],[14,15,16]])
np.hstack((a1,a2))


array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
# Ans:
# In NumPy, the numpy.flip() function is used to reverse the order of elements in an array along the given axis. Here, the shape of the array is
#   preserved, but the elements are reordered. It takes a specified axis or axes as a parameter along which to flip over the order of elements.
# numpy.fliplr() function is used to reverse the order of elements along axis 1 (left/right). Here, it is fixed that the elements will be reversed
#   along axis 1.For a 2-D array, this flips the entries in each row in the left/right direction. Columns are preserved but appear in a different
#   order than before.

In [ ]:
import numpy as np

arr= np.array([[9, 8, 3], [6, 2, 1]])
result = np.flipud(arr)
result

array([[6, 2, 1],
       [9, 8, 3]])

In [ ]:
import numpy as np

arr= np.array([[9, 8, 3], [6, 2, 1]])
result = np.fliplr(arr)
result

array([[3, 8, 9],
       [1, 2, 6]])

In [ ]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
# Ans:
# numpy.split() is a function that divides an array into equal parts along a specified axis. The code imports NumPy creates an array of numbers (0-5),
#  and then splits it in half (horizontally) using np.split(). The output shows the original array and the two resulting sub-arrays,
#   each containing 3 elements.
# If the array cannot be evenly divided, the behavior depends on the axis and the method used for splitting. For example, the numpy.array_split()
#  function allows uneven splits and handles any remaining elements. While numpy.split() divides the array into equal-sized sub-arrays,
#  numpy.array_split() can handle uneven splits.

In [ ]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
# Ans:
# Broadcasting: Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this
#            without making needless copies of data and usually leads to efficient algorithm implementations.
# Vectorization : a programming style where operations on a single piece of data, typically in a loop, are replaced by operations on entire
#                 arrays. Vectorisation can improve the performance of a code and can make the code more concise and easier to maintain.